### ISSUE TITLE
Code location help

### ISSUE THREAD

**Issue by purohit** [fiji/fiji#110]
Hello,

I'm looking for the code that implements the following feature: http://fiji.sc/Color_Image_Processing#Merging_transmitted_light_and_fluorescence_images

Can you point me to the source file and lines? Not for the GUI, for the algorithm.

Thanks!

**Comment by hinerm** [comment]
Hi @purohit 

There are a few options described in [the FAQ](There are a few options described in the FAQ: http://imagej.net/FAQ#How_do_I_see_the_source_code_for_a_command.3F)

Hope that helps!

**Comment by purohit** [comment]
I think I found it: https://github.com/imagej/ImageJA/blob/6a554eec59315c9f0550bb17fdf1146cdae991a2/src/main/java/ij/plugin/RGBStackMerge.java#L262
