### ISSUE TITLE
Sholl Analysis 3.4.4

### ISSUE THREAD

**Issue by tferr** [fiji/fiji#111]
Hi!
This is just to let you know that Sholl Analysis v3.4.4 has just been [released](https://github.com/tferr/ASA/releases/tag/3.4.4). Could it be uploaded?

There seems to be problem, though:
After the release (tferr/ASA@0eb95a1), I've committed new changes (tferr/ASA@4b5df12) (the latter were just to update release notes), and the Jenkins job triggered by it seems to have [failed](http://jenkins.imagej.net/job/Sholl-Analysis/). I went through the [console log](http://jenkins.imagej.net/job/Sholl-Analysis/75/console). I realize now, that this is the first time I commit to a release version without incrementing the next release cycle (in this case 3.4.5-SNAPSHOT). Did I screw things up?

**Comment by hinerm** [comment]
Hi @tferr 

Congrats on the release!

> Did I screw things up?

It's mildly unfortunate that there are 2 commits with the same release version, and that is why the jenkins job failed (the 2nd commit triggered a build which it tried to deploy as 3.4.4, which already existed) but not a big deal. Just bump the version to a SNAPSHOT and you'll be fine!

>Could it be uploaded?

It would be great if you could submit a PR to update the [Sholl Analysis version in pom-fiji](https://github.com/fiji/pom-fiji/blob/pom-fiji-7.2.0/pom.xml#L204). That way we can keep the Fiji source synchronized with the Fiji update site! :)

Were you following any instructions for releasing Fiji projects? I'd like to update any documentation to make sure it discusses pom-fiji versions.

**Comment by hinerm** [comment]
Sholl Analysis 3.4.4 is now on the Fiji update site!

**Comment by tferr** [comment]
Thanks @hinerm!

Hopefully you will not think I am lazy. This is just how I've done in past, i.e., open a new issue here asking for you guys to upload the release version to the fiji update site.

> Were you following any instructions for releasing Fiji projects? I'd like to update any documentation to make sure it discusses pom-fiji versions.

Not really. So far, what I've done is a followup of this [discussion](https://github.com/fiji/fiji/pull/51#issuecomment-31765988).

**Comment by hinerm** [comment]
>Hopefully you will not think I am lazy.

Not at all! :)

>So far, what I've done is a followup of this discussion.

Thanks, I wasn't aware of this thread. I will discuss with @ctrueden on how we want to standardize this on the [wiki](imagej.net) at some point.

In the mean time, please don't hesitate to ask again when you need something uploaded, run into Jenkins problems, etc..
