### ISSUE TITLE
bootstrap.js is broken in Java 8

### ISSUE THREAD

**Issue by hinerm** [fiji/fiji#112]
Running `jrunscript bootstrap.js update-force-pristine` with the current bootstrap.js gives the error:

```
script error in file bootstrap.js : ReferenceError: "importClass" is not defined in bootstrap.js at line number 15
```
This can be worked around per [this SO post](http://stackoverflow.com/questions/22503100/java-8-javascript-engine-backwards-compatibility)

However, then we get the error:

```
script error in file bootstrap.js : TypeError: Cannot read property "printStackTrace" from undefined in bootstrap.js at line number 77
```

Not sure how to resolve this, but can be worked around by commenting out the `handleException` definition.

Then, `update-force-pristine` will run... a db.xml.gz will be downloaded, but we get another failure:
```
script error in file bootstrap.js : TypeError: Cannot call undefined in bootstrap.js at line number 316
```
meaning IJ is undefined.

**Comment by ctrueden** [comment]
It is broken because: imagej/imagej#116

**Comment by ctrueden** [comment]
@dscho I presume that https://github.com/imagej/imagej-updater/commit/a76bb7e416ddfeccc69bd7e7a72b672a88c5496a fixes this issue?

Also tangentially relevant: https://github.com/imagej/imagej/issues/116

**Comment by dscho** [comment]
> @dscho I presume that imagej/imagej-updater@a76bb7e fixes this issue?

I guess. It does so here.

**Comment by ctrueden** [comment]
Great.
