### ISSUE TITLE
loading big .zip (stack) does not work

### ISSUE THREAD

**Issue by StephanJanosch** [fiji/fiji#116]
I cannot open big stacks saved as zip.

Disabling SCIFIO (Edit -> Options-> ImageJ2)  resolved the loading issue. Now the zips load fine again.

**Comment by ctrueden** [comment]
Actually, I'd like to keep tracking this issue, so we can fix the behavior of ZIPs in SCIFIO. However, rather than reopen this issue here, I'll file a new issue in the appropriate SCIFIO component.
