### ISSUE TITLE
Fiji terminal grabs focus away from all terminals

### ISSUE THREAD

**Issue by axtimwalde** [fiji/fiji#118]
The Fiji Console grabs the focus away from all open windows in Ubuntu Unity 14.04 when generating System.out/err output.  In a situation where an error results in continuous System.out or err, I am unable to kill ImageJ or do anything else because I am unable to enter a terminal (Ctrl+Alt+F1 still works, but I cannot call xkill from there, but instead have to kill the process by its ID).  I understand that this is mainly a convenience issue but it is really disturbing.  The Console should not grab the focus ever.

**Comment by axtimwalde** [comment]
Answer to self: The event occurs only on System.err, not on System.out and is fixed in https://github.com/scijava/scijava-ui-swing/pull/9

**Comment by ctrueden** [comment]
Resolved by scijava/scijava-ui-swing#9. Will release and upload by end of next week.

**Comment by ctrueden** [comment]
Thanks @axtimwalde for the fix!
