### ISSUE TITLE
Make sure all JAR files include a manifest

### ISSUE THREAD

**Issue by ctrueden** [fiji/fiji#120]
The following JARs are currently missing a `META-INF/MANIFEST.MF`:
- plugins/Algorithm_Launcher.jar
- plugins/FFMPEG_IO.jar
- plugins/ij-ImageIO_.jar

Also these from the Stowers update site:
- plugins/Jay_Plugins.jar
- plugins/Jay_Plugins2.jar

Each JAR that is missing a manifest causes two (apparently harmless) NPEs to be thrown in the startup of the Trainable Weka Segmentation plugin; see [this thread](http://imagej.1557.x6.nabble.com/Trainable-Weka-Segmentation-Result-image-calibration-tp5012265p5012467.html) for related discussion.

/cc @iarganda

**Comment by ctrueden** [comment]
As an aside: since we cannot control all third party update sites, it would probably be good if the TWS plugin somehow suppressed these specific NPEs unless debugging mode is enabled.

**Comment by iarganda** [comment]
Can we do that from TWS if the exception is caught in the weka library?

**Comment by ctrueden** [comment]
Oh, it catches it and then dumps it to stderr? That's unfortunate. It can be worked around, but is more annoying. Best would be to fix it on the weka side, of course.

**Comment by iarganda** [comment]
I'll write to them!

**Comment by ctrueden** [comment]
@iarganda Any word from the weka developers on suppressing this exception? These exceptions that TWS pops when it is first run are pretty scary for users.

**Comment by ctrueden** [comment]
I guess this problem went away with the weka upgrade? At least: I'm not seeing those exceptions anymore in an up-to-date installation on my system.

And all JARs that are officially still part of the ImageJ and Fiji software stacks do include manifests now. So I'd say this issue is thoroughly closed.
