### ISSUE TITLE
Run R script

### ISSUE THREAD

**Issue by damisiak** [fiji/fiji#125]
Hi,

I use rJava to connect to R and run R scripts from within java. Where should the scripts be stored in Fiji? I saw a folder called scripts in the Fiji directory including some .m Matlab files, is this the right place?

Best, Danny.

**Comment by ctrueden** [comment]
Putting them in `scripts/` seems fine to me. If nowhere else seems to work, you can also put anything in the `lib/` subtree (creating it if needed) and the ImageJ Updater will allow you to upload it.

By the way, do you know about the [scripting-r](https://github.com/scijava/scripting-r) project? Would be great if someone had time to take ownership and finally polish that enough to add it to Fiji! Then you wouldn't have to maintain your own custom solution.
