### ISSUE TITLE
Monitor memory is broken

### ISSUE THREAD

**Issue by hinerm** [fiji/fiji#126]
Works in ImageJ 1.49v still, but opens a blank window in Fiji.

**Comment by hinerm** [comment]
Note that this breakage is a result of a change in IJ 1.x, as monitor memory still works in 1.48v.

**Comment by ctrueden** [comment]
* Works with 2.0.0-rc-30/1.49u without Fiji.
* Works with 2.0.0-rc-31/1.48v without Fiji.
* Broken in 2.0.0-rc-31/1.49v without Fiji.
* Broken in 2.0.0-rc-31/1.50a11 without Fiji.

**Comment by ctrueden** [comment]
So this issue more properly belongs in https://github.com/imagej/imagej, as it is not Fiji-specific.

**Comment by ctrueden** [comment]
Working with 2.0.0-rc-59/1.51n with Fiji. Presumed fixed.
