### ISSUE TITLE
bigwarp broken

### ISSUE THREAD

**Issue by bogovicj** [fiji/fiji#132]
Bigwarp is broken in the current fiji ( since bigdataviewer was updated to 2.0.x)

I just cut a new release to fix it (see below), as well as a new release of the dependency jitk-tps.
Please update the pom-fiji with these new version numbers:
* jitk-tps 1.2.1
   * ( saalfeldlab/jitk-tps@3231195a44032f64353f94187dad09a7b45c7857 )
* bigwarp_fiji 1.1.0
   * ( saalfeldlab/bigwarp@4030a53c4fbe77d96111088071c1c266a65d170b )

Note - jitk-tps 1.2.1 is already [tracked](http://maven.imagej.net/index.html#nexus-search;quick~jitk) in maven.imagej.net
but bigwarp_fiji 1.1.0 is [not](http://maven.imagej.net/index.html#nexus-search;quick~bigwarp)

Thanks as always!

**Comment by ctrueden** [comment]
@bogovicj Still working on aspects of this, but the POM changes are on master now at least.

**Comment by bogovicj** [comment]
@ctrueden Thanks!
