### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by axtimwalde** [fiji/fiji#134]
A fresh checkout on a computer with vanilla maven reveals this

    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 1:09.799s
    [INFO] Finished at: Thu Jan 14 14:35:48 EST 2016
    [INFO] Final Memory: 33M/964M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal on project fiji: Could not resolve dependencies for project sc.fiji:fiji:jar:2.0.0-SNAPSHOT: The following artifacts could not be resolved: sc.fiji:Simple_Neurite_Tracer:jar:3.0.1, sc.fiji:Volume_Calculator:jar:2.0.1: Could not find artifact sc.fiji:Simple_Neurite_Tracer:jar:3.0.1 in imagej.public (http://maven.imagej.net/content/groups/public) -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by axtimwalde** [comment]
For both artifacts, only 3.0.0 or 2.0.0 are available respectively.  I have to clarify that I upgraded to pom-fiji-21.0.0, This is a bug in pom-fiji https://github.com/fiji/pom-fiji/issues/8

**Comment by hinerm** [comment]
@axtimwalde thanks for following up on this. It's my fault for cutting the new pom-fiji. I thought these components were about to be released. Will follow up in pom-fiji
