### ISSUE TITLE
binary mask save as nifti format 

### ISSUE THREAD

**Issue by doctorbulat** [fiji/fiji#139]
Can you help me please! I have very stupid question. How to save a binary mask in NIFTI format? In 'save as' there are so many formats, but nifti is absent...

**Comment by imagejan** [comment]
Bio-Formats (which is included in Fiji) supports [import, but not export of NIFTI images](http://www.openmicroscopy.org/site/support/bio-formats5.1/formats/index.html). It's recommended to use an open format (e.g. [OME Tiff](http://www.openmicroscopy.org/site/support/ome-model/)) for saving.

That said, there is a [NIFTI input/output](http://imagej.net/plugins/nifti.html) plugin that you might want to check out.

**Comment by doctorbulat** [comment]
Thank you very much for good advice!
