### ISSUE TITLE
Fiji doesn't display all text (labels) of menu items and files.

### ISSUE THREAD

**Issue by SarenT** [fiji/fiji#148]
Hi,

I have realized that Fiji doesn't display all the text/labels anymore. This annoying, since I don't know by heart, where each menu item is. I didn''t use it for while and since my last usage, I have upgraded my Ubuntu from 14.04 to 16.04. Please see the screenshots I have taken:
![fiji problem](https://cloud.githubusercontent.com/assets/2906565/18386906/de576990-7699-11e6-826d-c7292b675e5a.png)

Updater tells me that it is up to date.
ImageJ: 1.5.1f
Java 1.6.0_24 (64-bit) (according to ImageJ)

Is there any known solution to this bug? or a workaround?

Thanks!

**Comment by ctrueden** [comment]
This is a bug in the interaction between Linux and Java 6. Try upgrading to Java 8:

*  ```bash
    sudo apt install openjdk-jdk-8
    ```
* Rename your `Fiji.app/java` folder to `Fiji.app/java6`.
* Start Fiji. It should say `1.8.0_101` or similar for the [Java version in the status bar](http://imagej.net/Troubleshooting#Checking_the_Java_version).

Optionally, [enable the Java-8 update site](http://imagej.net/2016-05-10_-_ImageJ_HOWTO_-_Java_8,_Java_6,_Java_3D) to receive the latest updates:

* Choose _Help &#9654; Update..._ to launch the [Updater](http://imagej.net/Updater).
* Click the "Manage update sites" button.
* Tick the `Java-8` box.
* Download the boatload of updates.
* Restart Fiji.

If anything goes wrong, you can always [download a fresh Fiji](http://fiji.sc/#download) to get a very recent version with the Java-8 update site enabled.

**Comment by SarenT** [comment]
It indeed solved the issue. Thanks a lot!
