### ISSUE TITLE
Problems with securely accessing https://imagej.net

### ISSUE THREAD

**Issue by paulmenzel** [fiji/fiji#149]
Currently securely accessing the [ImageJ Web site](https://imagej.net) is not possible, as assets are linked over HTTP and not HTTPS (mixed content), which the browser blocks.

![20160915 imagej https mixed content](https://cloud.githubusercontent.com/assets/9318792/18544897/255fc25a-7b37-11e6-8515-5f047035ea6d.png)

**Comment by ctrueden** [comment]
Indeed, this is a known issue. We only recently deployed HTTPS across all LOCI servers, and some of the domains including imagej.net are not fully set up yet—hence the lack of announcement.

In future, please file ImageJ issues at https://github.com/imagej/imagej/issues. This repo is for Fiji-specific things.

**Comment by paulmenzel** [comment]
Thank you for the quick response. I am sorry that I missed the link in the box at the [page *Report a Bug*](http://imagej.net/Report_a_Bug), and followed the link *BugZilla*.

**Comment by ctrueden** [comment]
@aneevel FYI. See above; people anxiously await full HTTPS support!

**Comment by ctrueden** [comment]
The HTTPS support has been complete for quite some time now.
