### ISSUE TITLE
Additional point after the third decimal in results

### ISSUE THREAD

**Issue by lbuchegger** [fiji/fiji#158]
I am analysing the area and diameter (Feret´s diameter) of more or less roundish objects on my pictures in FIJI, via transforming them to binary and further modifying them. However, via Analyze particles and Measurement in the ROI manager sometimes there are point added to the results behind the third decimal if you save the results an dopen them in Excel. In some pictures there are no commas at all, but in others almost every result has this additional comma. It seems to be more often in the diameter than in the area. As far as I have seen, this does not change the results at all, it is just annoying to delete these additional points.

**Comment by imagejan** [comment]
Are you sure you're not confounding thousands separator and decimal separator here? Which locale does your Excel use? If it's using a comma as decimal separator, you'll have to explicitly switch to `.` for importing data from ImageJ, as ImageJ/Fiji always use the dot, independent of the system's locale.

**Comment by lbuchegger** [comment]
You are right. I double checked it and it seems that this is the problem.
Thanks a lot for your help
