### ISSUE TITLE
ImageJ net is running insecurely

### ISSUE THREAD

**Issue by lizcw** [fiji/fiji#166]
I have just come to the http://imagej.net in the hope to contribute an ImageJ plugin but am surprised and dismayed to see that it is running insecurely.  It should be running over https, especially where participants are expected to enter account details as currently the username and passwords will be sent in plain text.

**Comment by ctrueden** [comment]
@lizcw The site does support HTTPS. Just change `http:` to `https:` and you should be secure.

We do not yet redirect all `http` traffic to `https` because doing so can have negative technical ramifications in various ways. So I want to hold off on forcing everyone to HTTPS for a bit longer.

**Comment by lizcw** [comment]
Thanks for letting me know.  I have set up whole sites over https without seeing any adverse issues - perhaps at least the login pages could be redirected?  Regards Liz

**Comment by ctrueden** [comment]
Closing, since imagej.net is accessible over HTTPS, and anyway this issue is not related to Fiji.

Eventually, we will probably redirect all HTTP traffic to HTTPS, but not until after some more pressing work on the servers.

**Comment by ctrueden** [comment]
> Eventually, we will probably redirect all HTTP traffic to HTTPS

For `imagej.net` itself, I have now instituted a blanket HTTP-to-HTTPS redirect. See [this topic](http://forum.imagej.net/t/imagej-net-http-blanket-redirect-to-https/5730) for details.
