### ISSUE TITLE
Fiji for linux not launching

### ISSUE THREAD

**Issue by vkehayas** [fiji/fiji#170]
Freshly installed Fiji refuses to launch in debian 9:

```
:~/bin/Fiji.app$ ./ImageJ-linux64
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
fish: “./ImageJ-linux64” terminated by signal SIGSEGV (Address boundary error)
```

I see that a possibly similar issue was fixed for windows and mac (e.g.):
http://fiji.sc/bug/1008.html

Also possibly related bug: https://github.com/fiji/fiji/issues/122 (renaming Fiji.app/java to java.bak did not solve the issue).

`jdk1.8.0_66` is included in `Fiji.app/java/linux-amd64
`
```
uname -a
Linux [...] 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u1 (2017-06-18) x86_64 GNU/Linux
```

**Comment by ctrueden** [comment]
This is being discussed [here on the forum](http://forum.imagej.net/t/unable-to-start-imagej-on-ubuntu-16-04-2-fresh-install/5757).
