### ISSUE TITLE
Save individual segmented objects as individual image files

### ISSUE THREAD

**Issue by saanasum** [fiji/fiji#178]
Is there a possibility in Fiji to save individual segmented objects as individual image files?

My goal is to automatically detect all nuclei in a FISH image and afterwards save each nucleus as separate image file. 

I would like to do this for a large batch of FISH images.

**Comment by ctrueden** [comment]
@saanasum Yes, you can do it with an [ImageJ macro](https://imagej.net/Macros) such as the following:
```javascript
#@ File (style = "directory") outputDir

// Demo part -- to show it works.
run("Blobs (25K)");
setAutoThreshold("Default");
run("Analyze Particles...", "exclude clear add");

// Code for looping ROIs and saving them.
setBatchMode(true);
for (i=0; i<roiManager("count"); i++) {
	run("Duplicate...", " ");
	roiManager("deselect");
	roiManager("select", i);
	// NB: Uncomment the next two lines if you want to clear the background before saving.
	//setBackgroundColor(0, 0, 0);
	//run("Clear Outside");
	run("Crop");
	saveAs("Tiff", outputDir + "/object-" + i + ".tif");
	close();
}
```
If you have further questions about Fiji usage, please don't hesitate to post them on the [ImageJ Forum](http://forum.imagej.net/). We use GitHub Issues here more for developers, to keep track of bugs and feature requests.

**Comment by saanasum** [comment]
Many thanks!
