### ISSUE TITLE
Fiji fails after update (+ adding update sites)

### ISSUE THREAD

**Issue by ThomasLauney** [fiji/fiji#183]
Hello,
From a fresh install (which was working) on Win7 64
After the last update (and adding BIG, biomed and Omero), I see the splash screen, Fiji windows opens transiently then is gone. Below is the copy of debug:
Any help most welcome
 
find_newest: searching 'C:\fiji\Fiji.app/java' for 'jre/bin/server/jvm.dll'
find_newest: file not found: 'C:\fiji\Fiji.app/java/jre/bin/server/jvm.dll'
find_newest: searching 'C:\fiji\Fiji.app/java/win64' for 'jre/bin/server/jvm.dll
'
find_newest: file not found: 'C:\fiji\Fiji.app/java/win64/jre/bin/server/jvm.dll
'
find_newest: searching 'C:\fiji\Fiji.app/java/win64/jdk1.8.0_66' for 'jre/bin/se
rver/jvm.dll'
find_newest: found a candidate: 'C:\fiji\Fiji.app/java/win64/jdk1.8.0_66'
Detected ImageJ2
JRE not found in 'C:\fiji\Fiji.app/jre'
JAVA_HOME contains a JRE: 'C:\fiji\Fiji.app/java/win64/jdk1.8.0_66//jre'
Available RAM: 32692MB, using 3/4 of that: 24519MB
java -Dpython.cachedir.skip=true -Dplugins.dir=C:\\fiji\\Fiji.app -Xmx24519m -Xi
ncgc -XX:PermSize=128m -Djava.class.path=C:\\fiji\\Fiji.app/jars/imagej-launcher
-4.0.5.jar -Dimagej.dir=C:\\fiji\\Fiji.app -Dij.dir=C:\\fiji\\Fiji.app -Dfiji.di
r=C:\\fiji\\Fiji.app -Dfiji.defaultLibPath=bin/server/jvm.dll -Dfiji.executable=
C:\\fiji\\Fiji.app\\debug.exe -Dij.executable=C:\\fiji\\Fiji.app\\debug.exe -Dja
va.library.path=C:\\fiji\\Fiji.app/lib/win64;C:\\fiji\\Fiji.app/mm/win64 -Dscija
va.context.strict=false -Dij.debug=true -Dscijava.log.level=debug net.imagej.lau
ncher.ClassLauncher -ijjarpath jars -ijjarpath plugins net.imagej.Main 1>stdout.
txt 2>C:\\fiji\\stderr.txt 3>foo.txt
Using JAVA_HOME C:\fiji\Fiji.app/java/win64/jdk1.8.0_66//jre
Opening Java library C:\fiji\Fiji.app/java/win64/jdk1.8.0_66//jre/bin/server/jvm
.dll
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=128m; suppor
t was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated a
nd will likely be removed in a future release
Adding option: -Djava.home=C:\fiji\Fiji.app/java/win64/jdk1.8.0_66/
ij1.plugin.dirs: null
$HOME/.plugins: C:\Users\SMMP_Fiji\.plugins does not exist
Launching main class net.imagej.Main with parameters [1>stdout.txt, 2>C:\fiji\st
derr.txt, 3>foo.txt]
Class loader = sun.misc.Launcher$AppClassLoader@764c12b6
Checking class loader: sun.misc.Launcher$AppClassLoader@764c12b6
Checking URL: file:/C:/fiji/Fiji.app/jars/imagej-launcher-4.0.5.jar
Not Eclipse because first entry is: file:/C:/fiji/Fiji.app/jars/imagej-launcher-
4.0.5.jar
[DEBUG] Creating service: org.scijava.event.DefaultEventService
[DEBUG] Creating service: org.scijava.log.slf4j.SLF4JLogService
[DEBUG] Created service 'org.scijava.log.slf4j.SLF4JLogService' in 162 ms
[DEBUG] Creating service: org.scijava.thread.DefaultThreadService
[DEBUG] Created service 'org.scijava.thread.DefaultThreadService' in 1 ms
[DEBUG] Created service 'org.scijava.event.DefaultEventService' in 205 ms
[DEBUG] Creating service: net.imagej.legacy.LegacyConsoleService
[DEBUG] Creating service: net.imagej.legacy.LegacyService
[DEBUG] Creating service: org.scijava.command.DefaultCommandService
[DEBUG] Creating service: org.scijava.plugin.DefaultPluginService
[DEBUG] Created service 'org.scijava.plugin.DefaultPluginService' in 1 ms
[DEBUG] Creating service: org.scijava.module.DefaultModuleService
[DEBUG] Creating service: org.scijava.object.DefaultObjectService
[DEBUG] Created service 'org.scijava.object.DefaultObjectService' in 3 ms
[DEBUG] Creating service: org.scijava.prefs.DefaultPrefService
[DEBUG] Created service 'org.scijava.prefs.DefaultPrefService' in 3 ms
[DEBUG] Creating service: org.scijava.convert.DefaultConvertService
[DEBUG] Created service 'org.scijava.convert.DefaultConvertService' in 2 ms
[DEBUG] Created service 'org.scijava.module.DefaultModuleService' in 11 ms
[DEBUG] Created service 'org.scijava.command.DefaultCommandService' in 27 ms
[DEBUG] Creating service: org.scijava.options.DefaultOptionsService
[DEBUG] Created service 'org.scijava.options.DefaultOptionsService' in 1 ms
[DEBUG] Creating service: net.imagej.legacy.display.LegacyImageDisplayService
[DEBUG] Created service 'net.imagej.legacy.display.LegacyImageDisplayService' in
 3 ms
[DEBUG] Creating service: org.scijava.script.DefaultScriptService
[DEBUG] Creating service: org.scijava.app.DefaultAppService
[DEBUG] Created service 'org.scijava.app.DefaultAppService' in 2 ms
[DEBUG] Creating service: org.scijava.script.process.DefaultScriptProcessorServi
ce
[DEBUG] Created service 'org.scijava.script.process.DefaultScriptProcessorServic
e' in 1 ms
[DEBUG] Creating service: org.scijava.parse.DefaultParseService
[DEBUG] Created service 'org.scijava.parse.DefaultParseService' in 1 ms
[DEBUG] Created service 'org.scijava.script.DefaultScriptService' in 5 ms
[DEBUG] Creating service: org.scijava.app.DefaultStatusService
[DEBUG] Created service 'org.scijava.app.DefaultStatusService' in 1 ms
[DEBUG] Creating service: io.scif.services.SCIFIODatasetService
[DEBUG] Created service 'io.scif.services.SCIFIODatasetService' in 5 ms
[DEBUG] Creating service: org.scijava.display.DefaultDisplayService
[DEBUG] Created service 'org.scijava.display.DefaultDisplayService' in 2 ms
[DEBUG] Creating service: org.scijava.menu.DefaultMenuService
[DEBUG] Created service 'org.scijava.menu.DefaultMenuService' in 1 ms
[DEBUG] Creating service: net.imagej.display.DefaultOverlayService
[DEBUG] Creating service: net.imagej.ui.awt.AWTRenderingService
[DEBUG] Created service 'net.imagej.ui.awt.AWTRenderingService' in 1 ms
[DEBUG] Created service 'net.imagej.display.DefaultOverlayService' in 4 ms
[DEBUG] Creating service: net.imagej.threshold.DefaultThresholdService
[DEBUG] Created service 'net.imagej.threshold.DefaultThresholdService' in 2 ms
[DEBUG] Created service 'net.imagej.legacy.LegacyService' in 1566 ms
[DEBUG] Created service 'net.imagej.legacy.LegacyConsoleService' in 1568 ms
[DEBUG] Creating service: fiji.DefaultFijiService
[DEBUG] Created service 'fiji.DefaultFijiService' in 1 ms
[DEBUG] Creating service: org.scijava.console.DefaultConsoleService
[DEBUG] Created service 'org.scijava.console.DefaultConsoleService' in 2 ms
[DEBUG] Creating service: org.scijava.download.DefaultDownloadService
[DEBUG] Creating service: org.scijava.io.handle.DefaultDataHandleService
[DEBUG] Created service 'org.scijava.io.handle.DefaultDataHandleService' in 1 ms

[DEBUG] Creating service: org.scijava.task.DefaultTaskService
[DEBUG] Created service 'org.scijava.task.DefaultTaskService' in 1 ms
[DEBUG] Created service 'org.scijava.download.DefaultDownloadService' in 8 ms
[DEBUG] Creating service: org.scijava.event.DefaultEventHistory
[DEBUG] Created service 'org.scijava.event.DefaultEventHistory' in 1 ms
[DEBUG] Creating service: org.scijava.input.DefaultInputService
[DEBUG] Created service 'org.scijava.input.DefaultInputService' in 2 ms
[DEBUG] Creating service: org.scijava.io.DefaultIOService
[DEBUG] Created service 'org.scijava.io.DefaultIOService' in 1 ms
[DEBUG] Creating service: org.scijava.io.DefaultRecentFileService
[DEBUG] Created service 'org.scijava.io.DefaultRecentFileService' in 0 ms
[DEBUG] Creating service: org.scijava.io.nio.DefaultNIOService
[DEBUG] Created service 'org.scijava.io.nio.DefaultNIOService' in 0 ms
[DEBUG] Creating service: org.scijava.main.DefaultMainService
[DEBUG] Created service 'org.scijava.main.DefaultMainService' in 1 ms
[DEBUG] Creating service: org.scijava.platform.DefaultPlatformService
[DEBUG] Creating service: org.scijava.platform.DefaultAppEventService
[DEBUG] Created service 'org.scijava.platform.DefaultAppEventService' in 0 ms
[DEBUG] Created service 'org.scijava.platform.DefaultPlatformService' in 5 ms
[DEBUG] Creating service: org.scijava.run.DefaultRunService
[DEBUG] Created service 'org.scijava.run.DefaultRunService' in 1 ms
[DEBUG] Creating service: org.scijava.script.DefaultScriptHeaderService
[DEBUG] Created service 'org.scijava.script.DefaultScriptHeaderService' in 0 ms
[DEBUG] Creating service: org.scijava.search.DefaultSearchService
[DEBUG] Created service 'org.scijava.search.DefaultSearchService' in 1 ms
[DEBUG] Creating service: org.scijava.text.DefaultTextService
[DEBUG] Created service 'org.scijava.text.DefaultTextService' in 1 ms
[DEBUG] Creating service: org.scijava.tool.DefaultToolService
[DEBUG] Created service 'org.scijava.tool.DefaultToolService' in 3 ms
[DEBUG] Creating service: org.scijava.ui.DefaultUIService
[DEBUG] Created service 'org.scijava.ui.DefaultUIService' in 3 ms
[DEBUG] Creating service: org.scijava.ui.dnd.DefaultDragAndDropService
[DEBUG] Created service 'org.scijava.ui.dnd.DefaultDragAndDropService' in 2 ms
[DEBUG] Creating service: org.scijava.ui.swing.SwingIconService
[DEBUG] Created service 'org.scijava.ui.swing.SwingIconService' in 0 ms
[DEBUG] Creating service: org.scijava.ui.swing.script.DefaultLanguageSupportService
[DEBUG] Created service 'org.scijava.ui.swing.script.DefaultLanguageSupportService' in 0 ms
[DEBUG] Creating service: org.scijava.welcome.DefaultWelcomeService
[DEBUG] Created service 'org.scijava.welcome.DefaultWelcomeService' in 1 ms
[DEBUG] Creating service: org.scijava.widget.DefaultWidgetService
[DEBUG] Created service 'org.scijava.widget.DefaultWidgetService' in 1 ms
[DEBUG] Creating service: org.scijava.log.StderrLogService
[DEBUG] Created service 'org.scijava.log.StderrLogService' in 0 ms
[DEBUG] Creating service: org.scijava.cache.DefaultCacheService
[DEBUG] Created service 'org.scijava.cache.DefaultCacheService' in 0 ms
[DEBUG] Creating service: io.scif.DefaultMetadataService
[DEBUG] Created service 'io.scif.DefaultMetadataService' in 0 ms
[DEBUG] Creating service: io.scif.codec.DefaultCodecService
[DEBUG] Created service 'io.scif.codec.DefaultCodecService' in 0 ms
[DEBUG] Creating service: io.scif.formats.qt.DefaultQTJavaService
[DEBUG] Created service 'io.scif.formats.qt.DefaultQTJavaService' in 2 ms
[DEBUG] Creating service: io.scif.formats.tiff.DefaultTiffService
[DEBUG] Created service 'io.scif.formats.tiff.DefaultTiffService' in 1 ms
[DEBUG] Creating service: io.scif.gui.DefaultGUIService
[DEBUG] Created service 'io.scif.gui.DefaultGUIService' in 2 ms
[DEBUG] Creating service: io.scif.img.DefaultImgUtilityService
[DEBUG] Created service 'io.scif.img.DefaultImgUtilityService' in 5 ms
[DEBUG] Creating service: io.scif.img.cell.cache.MapDBCache
[DEBUG] Creating service: io.scif.refs.DefaultRefManagerService
[DEBUG] Created service 'io.scif.refs.DefaultRefManagerService' in 1 ms
[DEBUG] Created service 'io.scif.img.cell.cache.MapDBCache' in 6 ms
[DEBUG] Creating service: io.scif.img.converters.DefaultPlaneConverterService
[DEBUG] Created service 'io.scif.img.converters.DefaultPlaneConverterService' in 1 ms
[DEBUG] Creating service: io.scif.io.DefaultNIOService
[DEBUG] Created service 'io.scif.io.DefaultNIOService' in 1 ms
[DEBUG] Creating service: io.scif.ome.services.DefaultOMEMetadataService
[DEBUG] Creating service: io.scif.services.DefaultFormatService
[DEBUG] Created service 'io.scif.services.DefaultFormatService' in 5 ms
[DEBUG] Creating service: io.scif.ome.services.DefaultOMEXMLService
[DEBUG] Created service 'io.scif.ome.services.DefaultOMEXMLService' in 17 ms
[DEBUG] Created service 'io.scif.ome.services.DefaultOMEMetadataService' in 26 ms
[DEBUG] Creating service: io.scif.services.DefaultDatasetIOService
[DEBUG] Created service 'io.scif.services.DefaultDatasetIOService' in 0 ms
[DEBUG] Creating service: io.scif.services.DefaultFilePatternService
[DEBUG] Created service 'io.scif.services.DefaultFilePatternService' in 1 ms
[DEBUG] Creating service: io.scif.services.DefaultLocationService
[DEBUG] Created service 'io.scif.services.DefaultLocationService' in 0 ms
[DEBUG] Creating service: io.scif.services.DefaultTranslatorService
[DEBUG] Created service 'io.scif.services.DefaultTranslatorService' in 0 ms
[DEBUG] Creating service: io.scif.services.JAIIIOServiceImpl
[DEBUG] Created service 'io.scif.services.JAIIIOServiceImpl' in 5 ms
[DEBUG] Creating service: io.scif.xml.DefaultXMLService
[DEBUG] Created service 'io.scif.xml.DefaultXMLService' in 50 ms
[DEBUG] Creating service: io.scif.services.DefaultInitializeService
[DEBUG] Created service 'io.scif.services.DefaultInitializeService' in 1 ms
[DEBUG] Creating service: net.imagej.lut.DefaultLUTService
[DEBUG] Created service 'net.imagej.lut.DefaultLUTService' in 1 ms
[DEBUG] Creating service: net.imagej.DefaultDatasetService
[DEBUG] Creating service: net.imagej.types.DefaultDataTypeService
[DEBUG] Created service 'net.imagej.types.DefaultDataTypeService' in 21 ms
[DEBUG] Created service 'net.imagej.DefaultDatasetService' in 23 ms
[DEBUG] Creating service: net.imagej.DefaultImgPlusService
[DEBUG] Created service 'net.imagej.DefaultImgPlusService' in 1 ms
[DEBUG] Creating service: net.imagej.animation.DefaultAnimationService
[DEBUG] Created service 'net.imagej.animation.DefaultAnimationService' in 2 ms
[DEBUG] Creating service: net.imagej.autoscale.DefaultAutoscaleService
[DEBUG] Created service 'net.imagej.autoscale.DefaultAutoscaleService' in 1 ms
[DEBUG] Creating service: net.imagej.display.DefaultImageDisplayService
[DEBUG] Created service 'net.imagej.display.DefaultImageDisplayService' in 1 ms
[DEBUG] Creating service: net.imagej.display.DefaultWindowService
[DEBUG] Created service 'net.imagej.display.DefaultWindowService' in 1 ms
[DEBUG] Creating service: net.imagej.display.DefaultZoomService
[DEBUG] Created service 'net.imagej.display.DefaultZoomService' in 0 ms
[DEBUG] Creating service: net.imagej.measure.DefaultMeasurementService
[DEBUG] Created service 'net.imagej.measure.DefaultMeasurementService' in 1 ms
[DEBUG] Creating service: net.imagej.measure.DefaultStatisticsService
[DEBUG] Created service 'net.imagej.measure.DefaultStatisticsService' in 0 ms
[DEBUG] Creating service: net.imagej.notebook.DefaultNotebookService
[DEBUG] Creating service: net.imagej.ops.DefaultOpService
[DEBUG] Creating service: net.imagej.ops.DefaultOpMatchingService
[DEBUG] Created service 'net.imagej.ops.DefaultOpMatchingService' in 2 ms
[DEBUG] Creating service: net.imagej.ops.DefaultNamespaceService
[DEBUG] Created service 'net.imagej.ops.DefaultNamespaceService' in 0 ms
[DEBUG] Created service 'net.imagej.ops.DefaultOpService' in 16 ms
[DEBUG] Created service 'net.imagej.notebook.DefaultNotebookService' in 18 ms
[DEBUG] Creating service: net.imagej.operator.DefaultCalculatorService
[DEBUG] Created service 'net.imagej.operator.DefaultCalculatorService' in 0 ms
[DEBUG] Creating service: net.imagej.sampler.DefaultSamplerService
[DEBUG] Created service 'net.imagej.sampler.DefaultSamplerService' in 2 ms
[DEBUG] Creating service: net.imagej.ui.DefaultImageJUIService
[DEBUG] Created service 'net.imagej.ui.DefaultImageJUIService' in 1 ms
[DEBUG] Creating service: net.imagej.ui.awt.AWTScreenCaptureService
[DEBUG] Created service 'net.imagej.ui.awt.AWTScreenCaptureService' in 0 ms
[DEBUG] Creating service: net.imagej.ui.swing.ops.DefaultOpFinderService
[DEBUG] Created service 'net.imagej.ui.swing.ops.DefaultOpFinderService' in 2 ms

[DEBUG] Creating service: net.imagej.ui.swing.overlay.JHotDrawService
[DEBUG] Created service 'net.imagej.ui.swing.overlay.JHotDrawService' in 2 ms
[DEBUG] Creating service: net.imagej.units.DefaultUnitService
[DEBUG] Created service 'net.imagej.units.DefaultUnitService' in 10 ms
[DEBUG] Creating service: net.imagej.updater.DefaultUpdateService
[DEBUG] Created service 'net.imagej.updater.DefaultUpdateService' in 4 ms
[DEBUG] Creating service: net.imagej.updater.DefaultUploaderService
[DEBUG] Created service 'net.imagej.updater.DefaultUploaderService' in 0 ms
[DEBUG] Creating service: net.imagej.display.DummyScreenCaptureService
[DEBUG] Created service 'net.imagej.display.DummyScreenCaptureService' in 0 ms
[DEBUG] Creating service: net.imagej.render.DummyRenderingService
[DEBUG] Created service 'net.imagej.render.DummyRenderingService' in 1 ms
Error while executing the main() method of class 'net.imagej.Main':
java.lang.AbstractMethodError: Method org/scijava/log/slf4j/SLF4JLogService.addLogListener(Lorg/scijava/log/LogListener;)V is abstract
        at org.scijava.log.slf4j.SLF4JLogService.addLogListener(SLF4JLogService.java)
        at org.scijava.ui.swing.console.SwingConsolePane.initLoggingPanel(SwingConsolePane.java:143)
        at org.scijava.ui.swing.console.SwingConsolePane.getComponent(SwingConsolePane.java:123)
        at net.imagej.legacy.ui.LegacyUI.createConsole(LegacyUI.java:156)
        at net.imagej.legacy.ui.LegacyUI.show(LegacyUI.java:144)
        at org.scijava.ui.DefaultUIService.showUI(DefaultUIService.java:157)
        at org.scijava.ui.DefaultUIService.showUI(DefaultUIService.java:142)
        at org.scijava.AbstractGateway.launch(AbstractGateway.java:103)
        at net.imagej.Main.main(Main.java:55)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at net.imagej.launcher.ClassLauncher.launch(ClassLauncher.java:279)
        at net.imagej.launcher.ClassLauncher.run(ClassLauncher.java:186)
        at net.imagej.launcher.ClassLauncher.main(ClassLauncher.java:77)

**Comment by imagejan** [comment]
> org.scijava.log.slf4j.SLF4JLogService

The `scijava-log-slf4j` component is served by the OMERO-5.2 update site:
http://sites.imagej.net/OMERO-5.2/jars/omero/

The version from this update site is pretty old (`scijava-log-slf4j-1.0.3.jar-20160914213814`), so guess this is a compatibility issue with the updated `scijava-common` in Fiji.

@ctrueden any ideas? Can `scijava-log-slf4j-1.0.5` be uploaded to that site?

**Comment by ThomasLauney** [comment]
Thanks Jan.
I deleted the \Omero and Fiji started normally. Downloaded 5.2.2 directly from OpenMicroscopy and UnZipped in \Plugin. Everything works. I send a note to OpenMicroscopy to suggest that their Update site may be should be "updated..." :-). Thanks for the quick diagnostic

**Comment by ctrueden** [comment]
I uploaded the newer `scijava-log-slf4j-1.0.5.jar` to the OMERO-5.2 update site.
