### ISSUE TITLE
"Find Ops..." menu item produces java IllegalArgumentException: No such field NAME

### ISSUE THREAD

**Issue by GenevieveBuckley** [fiji/fiji#187]
Selecting the Fiji "Find Ops..." menu item from:
Plugins > Utilities > Find Ops...
produces this java illegal argument exception:

```
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No such field: NAME
```

Contents of the Exception window & console log are attached as text files here.
[ConsoleLog.txt](https://github.com/fiji/fiji/files/1965557/ConsoleLog.txt)
[Exception.txt](https://github.com/fiji/fiji/files/1965558/Exception.txt)

Running the latest updated version of Fiji
* Version: 2.0.0-rc-65/1.52a
* Build: 961c5f1b7f
* Date: 2018-01-31T01:02:30+0000

MacOS High Sierra, version 10.13.4

**Comment by ctrueden** [comment]
Thanks for the report, @GenevieveBuckley! In response to this, I uploaded a new version of scijava-common to the update site. (Bug was actually fixed in the past day or so, but not uploaded till now.) Please update your Fiji and try again!

**Comment by GenevieveBuckley** [comment]
Wow, there are fast turnarounds, and then there's "oh yeah, the bug is ALREADY fixed". That's awesome!

Updating Fiji with the newest changes to scijava-common has done the trick. Since it seems to be working well now, I'm going to go ahead and close this issue.
