### ISSUE TITLE
copytoImgPlus.m does not work

### ISSUE THREAD

**Issue by kouichi-c-nakamura** [fiji/fiji#188]
`scripts/copytoImgPlus.m` does not work

In the following line, the code is trying to convert `ArrayImg` to `ImgPlus`, but it seems that there is no `ImgPlus` class in `imglib2` any longer. I could not find an equivalent either.

https://github.com/fiji/fiji/blob/e2824452ba3efc70f8352b0c09618cd09bc7fac5/scripts/copytoImgPlus.m#L136

Does anyone know a way to fix this?

**Comment by imagejan** [comment]
It should be [`net.imagej.ImgPlus`](http://javadoc.scijava.org/ImageJ/index.html?net/imagej/ImgPlus.html) from `imagej-common`.

**Comment by kouichi-c-nakamura** [comment]
Fixed as below:

```matlab
imgplus = net.imagej.ImgPlus(img, name, ax, calibration);
```

Issued an error:

```
No constructor 'net.imagej.ImgPlus' with matching signature found.
Error in copytoImgPlus (line 136)
imgplus = net.imagej.ImgPlus(img, name, ax, calibration); 
```

However `net.imagej.ImgPlus(img, name)` works fine.

`ax` is supposed to be `AxisType[]`  and it looks like `AxisType[]`:

```
ax =
  net.imglib2.meta.DefaultAxisType[]:
    [net.imglib2.meta.DefaultAxisType]
    [net.imglib2.meta.DefaultAxisType]
    [net.imglib2.meta.DefaultAxisType]
    [net.imglib2.meta.DefaultAxisType]
    [net.imglib2.meta.DefaultAxisType]
```

I wonder why it's been rejected. Any idea, please?

**Comment by kouichi-c-nakamura** [comment]
Fixed as below:

```matlab
imgplus = net.imagej.ImgPlus(img, name, ax, calibration);
```

Issued an error:

```
No constructor 'net.imagej.ImgPlus' with matching signature found.
Error in copytoImgPlus (line 136)
imgplus = net.imagej.ImgPlus(img, name, ax, calibration); 
```

However `net.imagej.ImgPlus(img, name)` works fine.

`ax` is supposed to be `AxisType[]`  and it looks like `AxisType[]`:

```
ax =
  net.imglib2.meta.DefaultAxisType[]:
    [net.imglib2.meta.DefaultAxisType]
    [net.imglib2.meta.DefaultAxisType]
    [net.imglib2.meta.DefaultAxisType]
    [net.imglib2.meta.DefaultAxisType]
    [net.imglib2.meta.DefaultAxisType]
```

I wonder why it's been rejected. Any idea, please?

**Comment by imagejan** [comment]
The axes should be using the [`net.imagej.axis.AxisType` interface](http://javadoc.scijava.org/ImageJ/index.html?net/imagej/axis/AxisType.html) now.

https://github.com/fiji/fiji/blob/c73992fa96c6be425c2a8f0f3858a3d5651336a3/scripts/copytoImgPlus.m#L53-L58

And these should accordingly be `net.imagej.axis.Axes.X` etc.

**Comment by kouichi-c-nakamura** [comment]
PR created 
https://github.com/fiji/fiji/pull/200
