### ISSUE TITLE
Multicore for Save as ZIP

### ISSUE THREAD

**Issue by hsyon** [fiji/fiji#193]
Hello,
Thank you all for your contributions to FIJI.
The "Save as ZIP" is very useful to reduce the file size.
However, this process doesn't seem to utilize all the cores in the processor, and I'm wondering if this could speed up saving to ZIP.
Thank you!
![multicore](https://user-images.githubusercontent.com/36607862/40629974-f1233902-628b-11e8-923f-46319a56ef9a.png)

**Comment by imagejan** [comment]
The *Save As > ZIP...* command is a feature of ImageJ 1.x ([`imagej/imagej1`](https://github.com/imagej/imagej1)), as it is implemented in the `FileSaver` class:

https://github.com/imagej/imagej1/blob/72849f7e54cee5cfba9526b402118576d88385f0/ij/io/FileSaver.java#L285-L328

Feature request like this are best addressed to @rasband directly.

**Comment by hsyon** [comment]
Hello,

After a quick search on the internet, found "pigz."

On MacOS, straightforward to compile.

--> multicore zip compression

test case
5.84 GB TIFF file
pigz -7 --zip --keep testfile.tif
--> 818 MB compressed file in a few minutes
ImageJ ZIP compression takes at least 10 minutes, etc and file size is 828.8 MB

with --fast option, compresses in seconds, but file size is somewhat larger.

The resulting .zip file can be opened directly from ImageJ.

thank you!

**Comment by imagejan** [comment]
In case someone stumbles upon this in the future, here's some interesting read about how to make saving to zip files faster with pure Java, using multi-threading: http://www.pixeldonor.com/2013/oct/12/concurrent-zip-compression-java-nio/
