### ISSUE TITLE
With ROI defined, no good way to advance one frame in stack

### ISSUE THREAD

**Issue by histed** [fiji/fiji#194]
With no ROIs defined, the left and right arrows step forward/back one frame in the stack, *without* changing the current display range.

(The < and > keys do the same, but they auto-recalculate the current display range, often not what is wanted when a stack was taken with its intensity range intended to be fixed, as in multi-timepoint imaging.)

With an ROI defined, the left and right arrows move the ROI, leaving no way I could find to step forward/back without changing the display range.  Is there a way to do this that I am missing?

**Comment by imagejan** [comment]
You should be able to use the arrow key while holding <kbd>Shift</kbd> pressed, no? In any case, this is not Fiji-specific, but rather an [`imagej1`](https://github.com/imagej/imagej1) issue, if at all.

**Comment by histed** [comment]
Thanks for looking at this.
On Mac, Shift-arrow keys still rescale the display intensity range.
I don't know who would be responsible for this, but we'd love to have a solution and I'd be happy to pass along this report to whoever you think is best; let me know whom.
thanks!

**Comment by imagejan** [comment]
@rasband any comments?

**Comment by rasband** [comment]
The latest ImageJ daily build (1.52d15) removes the "feature" that caused the display range to be changed when using keyboard shortcuts to step through a stack.

View the source code changes at
[https://github.com/imagej/imagej1/commit/d303eefea592f105de0c55fc0e3c54cc87da6862](url)
