### ISSUE TITLE
3D Viewer crash dump

### ISSUE THREAD

**Issue by alexn11** [fiji/fiji#197]
Using Fiji ImageJ 1.52c for Linux 64bits, Java version 1.8.0_172 (64 bits).

3D Viewer crashes at start up. From the FAQ of 3D Viewer "The 3D Viewer simply crashes".

Crash dump:
[hs_err_pid16309.log](https://github.com/fiji/fiji/files/2091995/hs_err_pid16309.log)

Message on the console:   
```

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f2ceb4ec1d8, pid=16309, tid=0x00007f2ca1b98700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_172-b11) (build 1.8.0_172-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.172-b11 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libawt_xawt.so+0x421d8]  ReadRegionsInList+0x3b8
#
# Core dump written. Default location: /home/alex/tmp/imagej/Fiji.app/core or core.16309
#
# An error report file with more information is saved as:
# /home/alex/tmp/imagej/Fiji.app/hs_err_pid16309.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

```

**Comment by ctrueden** [comment]
@alexn11 Thank you for the report, and sorry for the delay in reply.

The current situation with 3D Viewer is unfortunately rather intractable. See https://imagej.net/Java_3D. In the long term, we are developing a replacement plugin called [SciView](https://imagej.net/SciView) to address the technical problems of Java 3D and the 3D Viewer. In the immediate term, you could try using the Java 6 version of Fiji; see [here](http://imagej.net/Java_8) for instructions.
