### ISSUE TITLE
 can I change the gray level image to color image.

### ISSUE THREAD

**Issue by timeanddoctor** [fiji/fiji#198]
can I change the gray level image to color image.
![20180614205742](https://user-images.githubusercontent.com/28825816/41415006-19536050-701a-11e8-90b1-0d6aef74141b.jpg)

**Comment by imagejan** [comment]
Sure, you can use false-color lookup tables (LUTs), see the *Image > Lookup Tables* menu.

For questions like this, please use the [ImageJ forum](http://forum.imagej.net/), instead of opening a Github issue.
