### ISSUE TITLE
Adiposoft Manual Image Measurement

### ISSUE THREAD

**Issue by ghost** [fiji/fiji#202]
I have been using the adiposoft plugin in Fiji with the manual option so that I may add/delete objects. However, the output excel file created contains only the baseline data measured when the image is opened and not the updated information following additions/deletions.
ie. open image with adiposoft plugin, select manual settings, objects in imaged are traced, excel file created, select add, OK, trace object, click End, successful processed, results stored in file location X.
- Excel file does not include new object.

Your assistance is appreciated. Best, Aaron

**Comment by racox** [comment]
Please disregard my message. It looks like the final files were deposited in the Fiji application for some reason, instead of the designated folder.
