### ISSUE TITLE
 getDateAndTime() month returning wrong?

### ISSUE THREAD

**Issue by NickCondon** [fiji/fiji#203]
Current Date is 2018/07/31 yet FIJI is returning 2018/6/31??

See output from the following code:
```
getDateAndTime(year, month, week, day, hour, min, sec, msec);
print("Date: "+day+"/"+month+"/"+year);
```

Date: 31/6/2018

**Comment by ctrueden** [comment]
Thanks for cross-linking, @stelfrich!
