### ISSUE TITLE
FIJI Despeckle source code

### ISSUE THREAD

**Issue by awezmm** [fiji/fiji#213]
I cant seem to be find the java source code for the despeckle function. Where could I find it?

**Comment by imagejan** [comment]
Use the search bar (type <kbd>L</kbd>), search for "Despeckle", and press the <kbd>Source</kbd> button:

https://github.com/imagej/ImageJA/blob/173a8a337302362e954257aeb4214bbe4cd93c4b/src/main/java/ij/plugin/filter/RankFilters.java

In general, questions like this are much better asked on the forum (http://forum.image.sc), as this is not an issue report.
