### ISSUE TITLE
BigWarp buggy

### ISSUE THREAD

**Issue by bjtho08** [fiji/fiji#216]
The current version of BigWarp in repository (bigwarp_fiji-2.1.0) does not work correctly in the latest version of Fiji due to some change in how Fiji handles keypresses. It has been fixed in BigWarp 3.1.1 and onwards by changing how landmark mode is activated (instead of using space as a modifier, it is now a switch).

**Comment by imagejan** [comment]
An up-to-date Fiji installation should contain `bigwarp_fiji-3.1.2.jar` (shipped from the Java-8 update site).
I am unsure how you get version 2.1.0, do you have any other update sites activated?

**Comment by bjtho08** [comment]
I have the following update sites activated:

- ImageJ
- Fiji
- Java-8
- 3D ImageJ Suite
- BAR
- BaSiC
- BigStitcher
- HDF5
But I'm guessing none of them should overwrite the latest version?

**Comment by imagejan** [comment]
Are you sure you're actually running with Java 8? It seems 2.1.0 is the latest version shipped on the Fiji update site, but it would/should be overridden by an active Java-8 site.

Please check in the advanced mode of the updater to see where your `bigwarp_fiji` comes from.

**Comment by bjtho08** [comment]
I just checked and it appears that Java-8 is now correctly keeping bigwarp_fiji.jar up-to-date. Maybe I was just experiencing a random mistake. Previously, I had to download the newest jar-file manually and delete the 2.1.0 from my plugins-folder.

**Comment by bjtho08** [comment]
I will just go ahead and assume that it was a bug that has since been fixed.
