### ISSUE TITLE
ImageProcessor.fillOutside modifies Roi given as parameter

### ISSUE THREAD

**Issue by Dr-Frog** [fiji/fiji#219]
When the parameter to ImageProcessor is an Instance ShapeRoi, it will be modified within the function. To my understanding this happens in the line 

setRoi(s1.xor(s2));

as Roi.xor() modifies its caller.
Proposed solution is to change the line into

setRoi(s2.xor(s1));

**Comment by imagejan** [comment]
This is an `imagej/imagej1` issue, as the line you're talking about is here:

https://github.com/imagej/imagej1/blob/5d4538b93bfa127a3e28c48fc6ef68d5eb4933ea/ij/process/ImageProcessor.java#L1638

@rasband any comments?

**Comment by rasband** [comment]
The proposed fix is in the latest ImageJ daily build (1.52m44).
