### ISSUE TITLE
Brightness/contrast and other adjust boxes not opening properly

### ISSUE THREAD

**Issue by bio-nell** [fiji/fiji#222]

**Comment by imagejan** [comment]
Can you please provide more detail? Otherwise it's hard to reproduce the issue.

Are you using a multi-screen setup? Which version of Fiji/ImageJ are you using? Which operating system, etc. etc.

Maybe you can post a screenshot illustrating the issue?

**Comment by imagejan** [comment]
I just noticed you posted [*the same issue* on the forum](https://forum.image.sc/t/brightness-contrast-box-not-opening-properly/24197?u=imagejan). Please, when cross-posting, provide links to the respective other posts, so that people willing to help don't waste their time because they don't know others have replied already.

**Comment by bio-nell** [comment]
Hi, sorry for any confusion. This is my first time navigating these sites and I'm not sure how to provide links. Thank you for connecting them. I am on a second screen (monitor from a laptop) and haven't had this issue before. It persists on the laptop alone as well. 
Operating system: Windows 10, version 1809
ImageJ version: 1.52n
Java version: 1.8.0_172 (64-bit)
I have also attached a screenshot where I can see a grayed out brightness/contrast box (which I can't see at all on my regular screen). 
![2019-03-26 screenshot](https://user-images.githubusercontent.com/48956342/55007751-54fcb300-4fb6-11e9-958c-10eb7b9e570b.png)

**Comment by bio-nell** [comment]
Just for clarification, the grey box in the lower left hand corner I added to the screenshot for privacy.

**Comment by bio-nell** [comment]
After some troubleshooting I was able to fix this issue by right clicking the brightness/contrast window in the task bar. Selecting "move" and using arrow keys and then clicking the mouse. (just dragging with the mouse didn't work). Thank you and I will post this in the other forum as well.
