### ISSUE TITLE
Opening multi-page TIFF RGB (3x16b)

### ISSUE THREAD

**Issue by chacha21** [fiji/fiji#225]
I can generate multi-page TIFF with GDAL 3.0.0, each subdataset/page being RGB as 3x16bits. Windows Explorer is OK with such files, but ImageJ, even if it scans the pages properly at opening (it finds the correct count), raises an exception about unsupported stack.
Is it expected behaviour ?

With RGB as 3x8bits, there are no problems.

**Comment by ctrueden** [comment]
@chacha21 Please read https://imagej.net/TIFF to understand the status quo with TIFF in ImageJ. Unfortunately, there are multiple implementations of TIFF support.

Your best bet is probably to try _File › Import › Bio-Formats..._ and see if that addresses your issue. Another possibility is _Edit › Options > ImageJ2..._ and check the "Use SCIFIO" option, which will change how TIFF behaves by default.

If none of the different ways of importing TIFF works to read your particular TIFF files, then please place a sample non-working file somewhere, and we can investigate further.

**Comment by chacha21** [comment]
I did not think about those imports.
I will try it and if it does not work, I will post both an example and a minimal source code to generate.

**Comment by chacha21** [comment]
Both solutions (Bio formats and SCIFIO options) work. Proble solved.
:thumbsup:
