### ISSUE TITLE
Relocate MATLAB scripts

### ISSUE THREAD

**Issue by ctrueden** [fiji/fiji#234]
There are some `.m` scripts directly in the `scripts` folder (see https://github.com/fiji/TrackMate/issues/63#issuecomment-212956570). These should be relocated somewhere else, because `scripts/Foo/Bar` is now for scripts appearing in the _Foo &#9654; Bar_ menu. Probably nothing should be directly in the `scripts` folder.

**Comment by imagejan** [comment]
Only some of the scripts in the `scripts` folder are TrackMate-related. The others belong to the MATLAB interface (Miji) and are about to be migrated to `imagej-matlab`:

https://github.com/imagej/imagej-matlab/pull/19

We should decide however whether `script_templates` is the right place for those, or whether those script intended to be used _from_ Matlab (and not in the script editor) should live in some other folder.

**Comment by ctrueden** [comment]
Maybe scripts intended for use from MATLAB should live in `matlab/`? Or even subfolders like `matlab/TrackMate` to group them nicely?
