### ISSUE TITLE
Update Fiji bundles to use JetBrains JBRSDK 8

### ISSUE THREAD

**Issue by ctrueden** [fiji/fiji#240]
@skalarproduktraum wrote:
> i just spent some time making sciview work on hidpi displays with scaling applied. seems to work well now on windows and macos (haven't tested linux yet). however, this stuff working right is dependent on the jre exposing the surface scaling, which only works on java 9+ (bummer). but jetbrains to the help! they actually backported the fixes that expose the surface scaling right to java 8 (yay!).

We need to ship Fiji with a Java 8 on all platforms that meets the following criteria:

* JDK, not only JRE
* OpenJDK, not Oracle JDK
* Includes JavaFX (OpenJFX)
* Ideally, has the surface scaling stuff mentioned above

The only JDK that meets all requirements is the JetBrains JBR SDK.
We just need to:

* Download the JBR SDK for all five supported platforms:
    * https://confluence.jetbrains.com/display/JBR/JetBrains+Runtime
    * https://confluence.jetbrains.com/display/IDEADEV/JetBrains+Runtime+Environment
* Test on all supported platforms by placing the correct JBR SDK inside the `java` folder of a Fiji installation.
* Tweak the bundles as needed, based on test results.
* Replace the bundles [here](https://downloads.imagej.net/java/) with the good ones.

**Comment by hinerm** [comment]
@ctrueden on my windows machine, Fiji appears to work with JBRSDK8. 

Do we currently have build automation that can do that cross-platform test?

Is it actually sufficient to have a launcher that works with JBRSDK8 for this issue? Or, since we're creating an updated launcher, should we expand it to include the generalizing to work with the various Java 11 distributions, and so on?

**Comment by ctrueden** [comment]
Yes, we do have build automation that could do the test:
* https://travis-ci.org/imagej/imagej-launcher
* https://ci.appveyor.com/project/scijava/imagej-launcher

I designed the `check-java-version.sh` script as a good starting point, although portability (Windows in particular) probably needs more consideration. Something like your `run-java-gauntlet.sh` is just what I had in mind.

As for scope: I would prefer to generalize to the various distributions for Java 8/9/10/11/12/13/14 and ideally beyond, unless you find it starts taking a large quantity of time to do over cross-platform JBRSDK8 support.

**Comment by hinerm** [comment]
@ctrueden 

>I designed the check-java-version.sh script as a good starting point, although portability (Windows in particular) probably needs more consideration.

I just had to make a small tweak so it was agnostic of the launcher and it works fine on windows

>would be best to output system properties beyond just Java version, also including the path to the JDK (java.home etc.) to make sure the right JDK was picked up in each case.

Totally! I actually made the `run-java-gauntlet.sh` test the output of `check-java-version.sh` and [report success/failure](https://github.com/imagej/imagej-launcher/blob/c276b076fd0a3de10658fafabe8f48692744dfcf/run-java-gauntlet.sh#L36-L45) but we could move that check or change its behavior.

>As for scope: I would prefer to generalize to the various distributions for Java 8/9/10/11/12/13/14 and ideally beyond, unless you find it starts taking a large quantity of time to do over cross-platform JBRSDK8 support.

👍

**Comment by hinerm** [comment]
All [bundles](https://imagej.net/Fiji/Downloads) should now ship with Azul Java 8 JDK+FX, as of [this build](https://travis-ci.com/github/fiji/fiji-builds/builds/198246882)

**Comment by ctrueden** [comment]
The macOS download of Fiji still includes AdoptOpenJDK, not Zulu OpenJDK. See https://github.com/flimlib/flimj-ui/issues/23#issuecomment-963541622

**Comment by ctrueden** [comment]
This issue can now be closed (again). We decided to ship Zulu JDK+FX 8. The JetBrains JBR 8 is no longer available AFAICT; the [associated repository on GitHub](https://github.com/JetBrains/JetBrainsRuntime) only provides Java 11 and Java 17 flavors.
