### ISSUE TITLE
copy to system not copying all channels

### ISSUE THREAD

**Issue by cooketho** [fiji/fiji#241]
I'm having a problem when I try to use Edit->Copy to System where Fiji only copies some of the displayed channels but not others, or sometimes fails to copy the scale bar. I'm using MacOS Catalina 10.15.2 and the latest version of Fiji.

I've included an example file to reproduce the bug. I opened it with Fiji, and used the default Bio-Formats Import options. I then used shift+z to open the Channels window and selected "Composite" from the drop-down menu and checked Channel 1 and Channel 2. I then used Analyze->Tools->Scale Bar. At this point, Edit->Copy to System copies over an image that is missing the scale bar. I then used Image->Stacks->Z Project to make a maximum intensity projection. At this point, Edit->Copy to System copies over an image that has the scale bar and Channel 1, but is missing Channel 2.

Any ideas?

Thank you for any help you can give!

[control_1.lif.zip](https://github.com/fiji/fiji/files/4195146/control_1.lif.zip)

**Comment by cooketho** [comment]
Just wanted to add that this error also affects saved images as well, so it seems it is not just a clipboard-specific thing.

Please let me know if there is a workaround, or if it is likely to be fixed soon. At the moment, the program seems to be unusable for me.

Thank you!

**Comment by imagejan** [comment]
@cooketho I was able to reproduce this issue in an up-to-date Fiji on Windows 10 with the *Confocal Series* sample image.

I assume it's an ImageJ1 issue, as all the functionality affected is implemented in [`imagej/imagej1`](https://github.com/imagej/imagej1/).

/cc @rasband

**Comment by rasband** [comment]
The Edit>Copy to System command should work better with composite images in the latest ImageJ daily build (1.52u14). To upgrade, use the Help>Update ImageJ command and select "daily build" from the drop down menu.

**Comment by cooketho** [comment]
That works! Thank you!
