### ISSUE TITLE
Vagrant dev environment is broken

### ISSUE THREAD

**Issue by jotadepicas** [fiji/fiji#246]
Hi,
If you try to do a "vagrant up" you encounter two errors:

1. URL for precise64 box on hashicorp is not working. As per https://github.com/hashicorp/vagrant/issues/9897#issuecomment-395198639 a replacement URL could be https://vagrantcloud.com/hashicorp/boxes/precise64/versions/1.1.0/providers/virtualbox.box

2. openjdk-8-jdk package is not installable anymore via apt since Oracle made all those licensing changes, so the environment cannot be built. A different version of jdk like zulu for example could be used in replacement.

As a side comment, the vagrant environment is just way too old (ubuntu 12.04, 8 years), an also vagrant itself is quite heavy, maybe it's a good idea to move to docker.

Thanks.

**Comment by ctrueden** [comment]
Thanks @jotadepicas. I removed the outdated Vagrantfile. There is a Docker repo at https://github.com/fiji/dockerfiles, although it is also not really actively maintained right now.
