### ISSUE TITLE
Jython 2.7.2 released

### ISSUE THREAD

**Issue by acardona** [fiji/fiji#247]
Available here: https://www.jython.org/download

The major issue that motivates me to see the new jar distributed is the fixing of the bug related to loading classes in a multithreaded context.

How does one amend the pom.xml to include the new jython jar?

**Comment by imagejan** [comment]
This is already done in `scijava/scripting-jython`, see here:

https://github.com/scijava/scripting-jython/blob/c72f7d36fa133d3f9752d15edfa1c50d84b83595/pom.xml#L96-L111

**Comment by acardona** [comment]
Brilliant, thank you!
