### ISSUE TITLE
Can't add time stamper to hyperstack

### ISSUE THREAD

**Issue by JoBoPo** [fiji/fiji#284]
Hi, not sure what's going on but I am having problems adding time stamper to a hyperstack opened from a .nd file (either by selecting Stacks>TimeStamper or  automatically from a macro), which used to work without problems before.

However it might be related to the Bio-Formats recent update, as:

- it works, if I save this hyperstack, close it, open it and add time stamp
- it works, if I add time stamp after duplicating the hyperstack (either by creating a ROI or just by duplicating it)
- it works, if concatenating this original hyperstack with some other image
- it works, if converting this original hyperstack to an RGB

These are a few things I've tried, which let me think it might be something specific with the hyperstack opened directly from a .nd file.

I am using:
- 6.6.1 Bio-formats
- ImageJ 1.53J
- macOS Catalina, 10.15.6

Could you help me with this?

**Comment by imagejan** [comment]
Did you by chance open the hyperstack as "virtual stack" (showing `(V)` in the title)? If so, try deselecting this option in the Bio-Formats Importer dialog.

**Comment by JoBoPo** [comment]
oh yeah! That's it! Just tried and works now! Thank you so much :)
