### ISSUE TITLE
memory requirements at startup in a shared-access server ( HPC )

### ISSUE THREAD

**Issue by nollimahere** [fiji/fiji#290]
Dear devs,

I have a very strange situation that I need some input on regarding the startup of Fiji-2.2.0 in a shared-access server environment. 

I'm not sure whether to formally call this a 'bug' or not - but the problem is reproducible across multiple machines so please bear with me a moment while I try to explain.

TL;DR: 
Fiji starts up fine when I'm the sole user on an idle computer that has gobs of free memory available. But fails to startup the moment that there is someone else on the computer or the amount of free memory changes during Fiji's startup. 

Fiji also won't start at all when the free memory available is less than the total memory on the computer. When there is only 20GB free on a 80GB server, then Fiji complains about being unable to allocate the full 80GB in the JVM's heap.

The longer version:

I work in a research computing linux cluster which is admittedly under-powered for the amount of concurrent users that access the machines. This problem has only become worse during covid because everyone is remote now and suddenly the graphical machines ( nomachine on linux ) are now in very high demand.

I am able to work with Fiji-2.2.0 in an unattended manner using the cluster's job-scheduler just fine. But when I want to use the GUI in a NoMachine session, then I cannot reliably start Fiji because it complains about allocating a huge amount of memory in heap. Note, this amount of memory is not the same size even when the ImageJ-linux64 command runs a few seconds apart on the same machine.

Fiji-2.2.0 fails to finish it's startup on the server when someone else logs in and does work at the same time as me. For whatever reason Fiji is checks the total free memory somewhere during the initialization and actually tries to allocate all the free memory. Our JVM's don't restrict the heap size because reasons, but even when I try to set the heap size in JAVA_OPTS Fiji doesn't seem to care and still tries to allocate all the memory it can during startup.

Normally this has not been a problem for my workloads in previous versions of Fiji - the GUI starts up just fine.

Further, I can get the GUI to start on idle computers that nobody else is logged into. And then once I get past the startup, everything is fine even when other users happen to show up and start taking RAM for themselves.

So, 
If there is an undocumented switch that I can use to turn off this heap allocation check during startup then I'd be really happy to just turn on that switch and keep moving with Fiji-2.2.0.  But, if there is no ( easy? ) way to disable this check then I'd like to call this a 'bug' and work with you all to fix it.

I've attached a screenshot of the situation - please note the 2x different heap sizes that Fiji is complaining about - the first one was 64.59GB and the second one was 64.39GB.

<img width="1920" alt="Screen Shot 2021-07-14 at 4 11 46 PM" src="https://user-images.githubusercontent.com/26775002/125687515-a5431f91-9421-4800-a5a3-99b06be71df3.png">

**Comment by imagejan** [comment]
@nollimahere thanks for the report!

Did you try if any of the JVM flags of the launcher help? See https://imagej.net/learn/launcher

**Comment by tischi** [comment]
@nollimahere here another (maybe too old) thread for reference: https://forum.image.sc/t/set-memory-from-command-line-upon-startup-headless/8668/6
Does this help? 
(Even though your description indicates that something must have changed recently...)

**Comment by nollimahere** [comment]
Hi Tischi - thanks for the mention about the mem flag - that definitely does help stabilize the start-up.  

The only difference between the older versions and the newer version is the behavior when this --mem flag is not supplied. For whatever reason, the newer version is trying to grab all the memory on the computer during the startup.

So, I'm training my coworkers to check the free memory on a machine and set the --mem flag to be less than the physical max
