### ISSUE TITLE
Fix the filament detector issue - it messed up the Fiji 2.2.0 gateway

### ISSUE THREAD

**Issue by cyrilcros** [fiji/fiji#292]
Currently, following the `pyimagej` [initialization guide](https://github.com/imagej/pyimagej/blob/master/doc/Initialization.md) fails with the latest fiji 2.2.0 version, and it has done so for a long time. This is due to the `FilamentDetector-1.0.0` issues described here: https://forum.image.sc/t/fiji-fails-to-launch-after-update/44582
You get a confusing bug when trying something very simple like `ij=imagej.init('sc.fiji:fiji:2.2.0')`...

Could we please get new minor version of fiji that fixes it, even if relatively few commits have been made since Jan 16th / 2.2.0 ? You get errors right off the bat otherwise...
Thanks!

The commit were FilamentDetector was added is here: https://github.com/fiji/fiji/commit/2634bd7977a576205448aa0537d83abcb7e3e7ee

Cf https://github.com/fiji/fiji/issues/273

**Comment by cyrilcros** [comment]
I saw you fixed this on the Fiji gitter, thanks for all your work on ImageJ/Fiji!!!

**Comment by ctrueden** [comment]
@cyrilcros Yep, it's fixed on the Java side! But we do still need to make some updates to pyimagej et al. on the Python side to respect the versions inherited from the SciJava BOM. @hinerm is working on it... in the meantime, you may still have problems (not necessarily FilamentDetector 1.0.0 specifically, but problems) with `imagej.init('sc.fiji:fiji:2.3.0')`.
