### ISSUE TITLE
Unable to find FIJI 1.53f build in archive

### ISSUE THREAD

**Issue by orenwilcox** [fiji/fiji#297]
I’m having a bit of trouble downloading a specific FIJI build (1.53f) from the official archive. When I try to download any of the last 10 1.53 Win64 releases from [here](https://downloads.imagej.net/fiji/archive/), they all install to be 1.53c instead of the version they should be according to the [release notes](https://imagej.nih.gov/ij/source/release-notes.html). Is anyone experiencing a similar issue?

**Comment by mkitti** [comment]
See https://github.com/imagej/ij1-patcher/issues/50

**Comment by ctrueden** [comment]
@orenwilcox Fiji was stuck on ImageJ 1.53f for quite some time, but thanks to @mkitti's efforts (linked above), we were able to finally move past that. The current version of Fiji ships with ImageJ 1.53q.

Just in case it wasn't already clear: the versions 1.53f, 1.53q, etc., are versions of the [original ImageJ](https://imagej.net/software/imagej), *not* version numbers corresponding to releases of [ImageJ2](https://imagej.net/software/imagej2) nor [Fiji](https://imagej.net/software/fiji). When you click the title bar of a Fiji main window, you'll see a string such as "2.3.0/1.53q", which translates into "ImageJ2 2.3.0 + ImageJ 1.53q". This still doesn't tell you the version of *Fiji as a whole*, nor of any individual Fiji plugins, unfortunately. You can use the System Information command for that if you wish.
