### ISSUE TITLE
Latest update - script editor now hangs when opening scripts

### ISSUE THREAD

**Issue by hyungsongnam** [fiji/fiji#300]
Hello,
I'm using macOS Monterey 12.2.1, Oracle Java 8 update 321, and the no-jre Fiji.
The latest update brought in a script editor update.
Now, whenever I tried to open my .ijm scripts, it hangs the app. Please see the attached movie.
If I drag and drop to the Fiji window, it hangs every time.
If I open the script editor first, then open from "File - Open" it sometimes opens the script, and it sometimes hangs.
I can't think of a workaround for this right now, maybe I'll have to pause the updates with a fresh install.
Thank you.
Hyung-song Nam, PhD

https://user-images.githubusercontent.com/36607862/156863061-9a21e087-0514-4177-8357-0d25d4df3dc0.mov

**Comment by imagejan** [comment]
This should be tracked in https://github.com/scijava/script-editor.

But it *might* have been fixed already, @tferr is quite fast these days. See some related discussion [on the forum](https://forum.image.sc/t/shiny-new-script-editor/64160?u=imagejan).

**Comment by hyungsongnam** [comment]
Thanks for the reply.
I read the thread on the forum. Looks like others have also encountered the issues I encountered, and they are actively being fixed.
I'm in the middle of something now, but I will try the latest in a week or two.
I will close this here.
Thank you.
HN
