### ISSUE TITLE
Hello Would you like to ask if there are any other ways to deal with root length measurements quickly besides manual scribing measurements Need a side root total length solution

### ISSUE THREAD

**Issue by yungaiwood** [fiji/fiji#301]
![9](https://user-images.githubusercontent.com/99126022/160742390-bcae1e00-657d-4c3c-8b49-3c08d1a75bce.jpg)

**Comment by tischi** [comment]
Dear @yungaiwood,
The git issues are only for discussion of technical issues.
For image analysis issues, please ask on https://forum.image.sc/.

**Comment by yungaiwood** [comment]
ok thanks
