### ISSUE TITLE
Abberior msr Files

### ISSUE THREAD

**Issue by lucasSaavedra123** [fiji/fiji#302]
Hi,

We are trying to read Abberior msr files. I tried to read these types of files with ImageJ/Fiji and, although we can open them, Fiji shows some errors when we open these files. I was wondering if there is a way to know if these .msr files are corrupted or we really need Imspector software in order to read samples.

Images from Fiji are showed:

![image](https://user-images.githubusercontent.com/46687572/162093196-43adcea0-15bc-4b96-b263-e0f1e3d51469.png)

![image](https://user-images.githubusercontent.com/46687572/162093230-71cf856c-8789-4fdb-b522-669e5aa16d29.png)

There is [Pop] item and I don’t know its purpose neither.

**Comment by ctrueden** [comment]
@lucasSaavedra123 MSR formats are handled in Fiji by the [Bio-Formats](https://imagej.net/formats/bio-formats) library. On the [list of supported formats](https://docs.openmicroscopy.org/bio-formats/6.9.0/supported-formats.html) I see [Imspector OBF/MSR](https://docs.openmicroscopy.org/bio-formats/6.9.0/formats/imspector-obf.html) and [LaVision Imspector](https://docs.openmicroscopy.org/bio-formats/6.9.0/formats/lavision-imspector.html), but not Abberior.

However, from a discussion on the [Image.sc Forum](https://forum.image.sc/) it seems that others are opening Abberior MSR (if slowly):

* https://forum.image.sc/t/abberior-files-slow-to-open/51273

In any case, the errors you're seeing suggest a bug or limitation in Bio-Formats, so I advise you to [submit a Bio-Formats bug report](https://docs.openmicroscopy.org/bio-formats/6.9.0/about/bug-reporting.html#sending-a-bug-report). You can do this by making a post about it at https://forum.image.sc/ and tagging it with `bio-formats`.

**Comment by lucasSaavedra123** [comment]
Thank you very much @ctrueden
