### ISSUE TITLE
Update Bundled Java or replace with system Java.

### ISSUE THREAD

**Issue by mick-t** [fiji/fiji#304]
Hi,

On a server that I support for a Lab at Harvard Medical School I keep getting alerts from my security team about the version of Java that Fiji uses. For example:

"Plugin Output: 
The following vulnerable instances of Java are installed on the
remote host :

  Path              : /usr/local/Fiji.app/java/linux-amd64/jdk1.8.0_172
  Installed version : 1.8.0_172
  Fixed version     : 1.6.0_211 / 1.7.0_201 / 1.8.0_191 / 1.11.0_1"

Do you have any plans to update the Java version, or can I remove the Java version and system link to the version of Java installed system wide? If that works, that should keep my security happy as I can update the system java as needed. 

Thanks!
--Mick

**Comment by ctrueden** [comment]
> Do you have any plans to update the Java version

Yes! We were just discussing it on [this Image.sc Forum thread](https://forum.image.sc/t/feedback-needed-bundled-java-future-directions/44030/24?u=ctrueden). We will be updating the Fiji downloads very soon to bundle the latest [Zulu JDK+FX OpenJDK 8](https://www.azul.com/downloads/?version=java-8-lts&package=jdk-fx).

Unfortunately, the currently shipped version of the ImageJ Launcher native binary (version 5.0.3) is not smart enough to support different JDK directory structures such as Zulu's, so we need to tweak the directory layout to make it happy. We already made the ImageJ Launcher smarter with version 6.x, but we can't update the Fiji downloads to that version until we resolve some breakages preventing Fiji from launching on certain systems. Once we resolve these breakages, we will be able update Fiji to bundle Java 11 and then Java 17—they have the same problem where the 5.0.3 launcher can't detect them correctly, but the 6.x launcher can.

> can I remove the Java version and system link to the version of Java installed system wide?

Yes. You don't even need to make a symlink. Just rename the `Fiji.app/java` folder to some other name like `Fiji.app/java.disabled`. Then the ImageJ Launcher will search for system-wide Java installations, and finally fall back to the system Java on your path. You can use the "no-JRE" version of Fiji which comes without Java, and thus always searches for Java installed on your system.

This reminds me: we do need to make a decision now between Zulu JDK+FX and the JetBrains JBRSDK; see #240. We wanted to switch to the JBRSDK 8 before, but I vaguely recall there was some roadblock to doing so (e.g. maybe it doesn't work on some systems?).

**Comment by ctrueden** [comment]
Belated update to this issue: earlier this year, Fiji for all platforms was updated to ship with Zulu JDK+FX version 1.8.0_322.
