### ISSUE TITLE
Contrast enhancement code

### ISSUE THREAD

**Issue by vladtimug** [fiji/fiji#313]
Hi, does anybody know where I can find the code for the "Contrast Enhancement" option in Fiji? I am trying to replicate the behavior for this and the documentation is not enough because it does not specify how the algorothm works for multi channel images. (doc I read: https://homepages.inf.ed.ac.uk/rbf/HIPR2/stretch.htm#1)

**Comment by ctrueden** [comment]
@vladtimug You mean _Process &rarr; Enhance Contrast..._? It's [here](https://github.com/imagej/ImageJ/blob/v1.53t/ij/plugin/ContrastEnhancer.java). I found it by typing "enhance con" into the search bar, then clicking the <kbd>Source</kbd> button. (Unfortunately, the Source button is currently not-quite-right for commands from the original ImageJ; you have to strip the `src/main/java` from the resultant URL in the browser; I [fixed the bug](https://github.com/imagej/imagej-legacy/commit/67130792dc85bf26ffb313e59104e1cd3e40b45a) just now but I haven't released + uploaded the fix yet.)

**Comment by vladtimug** [comment]
@ctrueden many many thanks :)
