### ISSUE TITLE
ImageJ macro highlight does not work

### ISSUE THREAD

**Issue by remybonnav** [fiji/fiji#315]
Hi, 

I have problem with last fiji update.

Macro highlight for ImageJ macro language does not work anymore.

It is all black and white whereas for other languages it is working.

**Comment by remybonnav** [comment]
It is working if using a completely fresh new install

**Comment by ctrueden** [comment]
@remybonnav Sorry to hear you were having problems with the macro language highlighting. I'm assuming you all good now using the fresh install? Or if you still need assistance troubleshooting the broken installation, feel free to reopen the issue and comment here, and I can give some advice on how to compare your good install versus the bad one, to find differences that might be causing the issue (I'd start by checking the versions of the various JAR files in the `Fiji.app/jars` folder, as well as which update sites you have enabled).
