### ISSUE TITLE
Cropping BigTIFF images as virtual stack with Fiji is buggy

### ISSUE THREAD

**Issue by michihaa** [fiji/fiji#317]
I have a problem when cropping BigTIFF images with Fiji, but only if they are in virtual stack mode.

As I work with large image stacks and want to save them in a single file, I use the BigTIFF format. However, when I import those images into Fiji with Bio-Formats Importer as virtual stack and then crop the images, the resulting stack is just a sequence of identical frames and not the cropped parts from the original sequence.
If I load the original BigTIFF images into RAM (deselect the option "use virtual stack" in Bio-Formats importer window) and then crop the stack everything works as intended. So the problem only occurs in virtual stack mode.

In contrast, Z Project works for BigTIFF images in virtual stack, so this might be only a problem of the cropping tool.
As I work with images that are sometimes larger than the available RAM on my machine, using the virtual stack mode is necessary. So it would be very helpful if you cold fix this issue.

I'm running Fiji on Windows in the version 1.53t. I could reproduce the bug with another computer with freshly installed Fiji.
To generate the BigTIFF images I tried using the Bio-Formats Exporter as well as Python with the same result. So if you want to reproduce the bug easily you can use this python code to generate BigTIFFs:

```
import tifffile
import numpy as np

height = 400
width = 400
nSlices = 5

with tifffile.TiffWriter('test.tiff', bigtiff=True) as tif:
    frame = np.random.randint(256, size=(nSlices,height,width))
    tif.write(frame, contiguous=True)
```

Then load the sequence with Bio-Formats Importer as virtual stack. Select a ROI and crop the sequence. I then get 5 identical images.

Thanks a lot for the help,
Michael

**Comment by tischi** [comment]
Hi Michael,

Afaik, cropping a virtual stack in Fiji simply does not work. 
This is not really a bug, because it would require a completely new logic in the virtual stack that is not easy to implement.
If you don't mind loading the cropped region fully into RAM, you can "Duplicate" the selected ROI into a new stack.

**Comment by michihaa** [comment]
Hi tischi,

thanks a lot for this answer, that's exactly what I wanted. As for normal multi-page TIFF images the cropping worked, I was not aware of using "Duplicate" for this function.

Thank's a lot,
Michael
