### ISSUE TITLE
We need FIJI to handle "objects"

### ISSUE THREAD

**Issue by remybonnav** [fiji/fiji#318]
I think there are huge limitations in imageJ/Fiji in the sense that it does not handle "objects" but only ROIs.
It is really a pain to work with multiple selections and the fact that we cannot "filter" these ROIs (on size, on intensity of a specific channel, etc). 
For example many time one need to use analyze particle to filter outs some stuff and make single ROIs from a bigger ROI (selection of nuclei for example) but then we need to combine again all ROIs together create a new ROI and use it on another channel to mask out everything that is not in the nuclei.

It would be so much better to have a tool to filter objects from a large ROI that contain many independent non-touching ROIs.
This is especially true when we work with macro to automate al the process.

Is there a plugin already available in Fiji or do you think Fiji/imageJ developer could work on integrating "objects" ?

**Comment by imagejan** [comment]
@remybonnav thanks for your thoughts. I think this general request would be better suited as a post to https://forum.image.sc.

The [3D ImageJ Suite](https://imagej.net/plugins/3d-imagej-suite/index) has extensive functionality to deal with objects, including a 3D Object Manager. Would that fit your needs?
If you're more interested in scripting (e.g. in Groovy or Python/Jython), you can use the API of the [`imglib2-roi`](https://github.com/imglib/imglib2-roi/) library.
In any case, please open a topic on the forum to get assistance in using these, or also to discuss what's missing in the Fiji/ImageJ universe.

**Comment by remybonnav** [comment]
Thanks a lot for your reply.
I did a post in the forum.

Thanks again.

**Comment by imagejan** [comment]
Thanks.

For others finding this issue, [here's the forum topic](https://forum.image.sc/t/fiji-imagej-to-handle-objects/76558?u=imagejan).
