### ISSUE TITLE
Opening Multipage TIFFs as virtual stack per drag and drop

### ISSUE THREAD

**Issue by michihaa** [fiji/fiji#320]
Hello,
I found an interesting behavior in Fiji when opening Multipage-TIFFs as virtual stack per drag and drop. I was used to drag the TIFF file on the "More Tools" part (the two arrows on the right hand side of Fiji" to directly open the image as virtual stack. But this only worked for some files and not for all, so sometimes the files were directly loaded into RAM (which I didn't want to).
I found out that this depends on the extension of the images: for the extension *.tif the opening as virtual stack per drag and drop works, but for the newer *.tiff extension the file is always loaded into RAM.
I am using the newest Version 1.53t of Fiji on Windows 10.

Is it possible that you enable this option also for files with the *.tiff extension in a future version of Fiji?

Many thanks,
Michael

**Comment by rasband** [comment]
This bug is fixed in the ImageJ 1.54c29 daily build.

**Comment by rasband** [comment]
The latest ImageJ daily build (1.54c30) calls the Bio-Formats Importer for files dragged and dropped on the virtual stack field that can't be opened by the built in tiff reader.
