### ISSUE TITLE
New icon for MacOS

### ISSUE THREAD

**Issue by tianrui-qi** [fiji/fiji#355]
Is there any plan to adapt the app icon for FIJI to conform to the icon design of MacOs? Thanks

![image](https://github.com/user-attachments/assets/ac02eac5-23a9-40e9-848e-95ca08e034d3)

**Comment by ctrueden** [comment]
@tianrui-qi Yeah, we probably should. Thanks for filing this issue as a reminder. I personally hate the new design—it makes no sense to me to enclose already-round things into rounded rectangles—but I admit it's not great having Fiji stick out like a sore thumb either. I added this goal to the "Fiji Fit" project board whose goal is to bring various refreshments to Fiji.

**Comment by tianrui-qi** [comment]
> @tianrui-qi Yeah, we probably should. Thanks for filing this issue as a reminder. I personally hate the new design—it makes no sense to me to enclose already-round things into rounded rectangles—but I admit it's not great having Fiji stick out like a sore thumb either. I added this issue to the "Fiji Fit" project board whose goal is to bring various refreshments to Fiji.

Thanks!

**Comment by OratHelm** [comment]
In case it's any inspiration (we never know), I had made these two simple icons to personalize FIJI on my computer.

[fiji-macOS-icons.zip](https://github.com/user-attachments/files/17250403/fiji-macOS-icons.zip)

**Comment by tianrui-qi** [comment]
> In case it's any inspiration (we never know), I had made these two simple icons to personalize FIJI on my computer.
> 
> [fiji-macOS-icons.zip](https://github.com/user-attachments/files/17250403/fiji-macOS-icons.zip)

Thank you for sharing the FIJI macOS icons! They look great. If you’d like to make these icons available to a broader audience, you can try submitting them to [macosicons.com](https://macosicons.com/#/), a popular resource for macOS icon customization.

**Comment by ctrueden** [comment]
@OratHelm I took the liberty of uploading your awesome icons to the new Fiji update site. Within a week or two, the Updater will present a choice to either A) upgrade the Fiji installation to Java 21 and keep receiving updates (but also new bugs :wink:); or B) stay with Java 8 for maximum stability. Those who opt for option (A) on macOS will receive this new icon. It'll be very helpful for telling at a glance which flavor of Fiji a particular installation is! Thank you so much! :beers:
