### ISSUE TITLE
As of Oct 9 2024, the Fiji updater generates an error and doesn't work

### ISSUE THREAD

**Issue by hyungsongnam** [fiji/fiji#358]
Hello,
I'm not sure why but when I try to update the Fiji installation, I've been getting errors for the last few days.

![Screenshot 2024-10-09 at 2 13 36 PM](https://github.com/user-attachments/assets/680d76fe-6ed2-4a69-abb5-8213a5eca473)

![Screenshot 2024-10-09 at 2 20 35 PM](https://github.com/user-attachments/assets/324fd973-74aa-4245-abb6-a2a7aafe1f1f)

On a different machine, I wiped the installation clean, but in that instance, I now don't see any of the other update sites.
Thanks.
Sincerely,
Hyung-song Nam, PhD

**Comment by ctrueden** [comment]
Thank you for the report, @hyungsongnam! I have a suspicion what might have caused this, and will jump on fixing this immediately.
