### ISSUE TITLE
Duplicate jaunch items reported when launching

### ISSUE THREAD

**Issue by hinerm** [fiji/fiji#364]
On Windows x64 (non-arm). When opening [Fiji future](https://downloads.imagej.net/fiji/future/) I am told there are updates available. When I run the updater I get an error message that there are multiple up-to-date versions of everything in the `config/jaunch` directory (in reality, locally, there is only one version of each of these files - deleting the "duplicates" will, of course, ruin the installation)

If I ignore these updates and then continue updating, I get a couple new things - most notably a new version of `imagej-updater.jar`.

After applying the update and restarting these warnings are not present in future `Help > Update...` calls.

![image](https://github.com/user-attachments/assets/bd8c8833-5413-4ded-81bf-3f103ac6c276)

**Comment by ctrueden** [comment]
Yeah, this is super annoying. I was digging into it late last week, but haven't found the root cause yet. Definitely a bug in the the imagej-updater component, though.

**Comment by ctrueden** [comment]
Oh! I might have fixed this after all: imagej/imagej-updater@4b6d816471207dbfab1466b382db585b6a4c839a.

**Comment by ctrueden** [comment]
@hinerm Can you test the latest imagej-updater snapshot and see if this issue goes away? If so, we can cut a release.

**Comment by hinerm** [comment]
@ctrueden yep looks like that fixed it
