### ISSUE TITLE
Fiji future: unrecognized characters in toml

### ISSUE THREAD

**Issue by hinerm** [fiji/fiji#368]
(on Windows x64)
When I run the Fiji future launcher as-downloaded from the terminal I get:

```
[WARNING] [TOML] Ignoring unrecognized line segment: | (Ala∩┐╜∩┐╜:Nz
```

And actually this seems non-deterministic. On subsequent runs I get:

```
[WARNING] [TOML] Ignoring unrecognized line segment: | (Al∩┐╜m∩┐╜∩┐╜<∩┐╜-
```

```
[WARNING] [TOML] Ignoring unrecognized line segment: | (Alt∩┐╜V▌â∩┐╜-
```

Looking through the toml files I didn't see any clear correlation.

**Comment by ctrueden** [comment]
Maybe a mismatch between the file encoding on the file system vs how Jaunch is treating it?

**Comment by hinerm** [comment]
ok so it looks like `fiji.toml` and `jvml.toml` are unix-endline (`LF`) formatted while `python.toml` and `common.toml` are somehow windows-endline (`CRLF`) formatted. In particular something seems odd with the `python.toml` because if I change it to `LF` and save, the unknown character warning goes away! (even if `common.toml` is still CRLF)

All the files seem to be `LF` in GitHub so not sure what happened. But presumably if we replace the update site versions of these files with `LF` versions this will go away, and we may need to anyway as part of https://github.com/fiji/fiji/issues/364
