### ISSUE TITLE
Stop shipping unshaded fat jars

### ISSUE THREAD

**Issue by ctrueden** [fiji/fiji#83]
A "fat jar" is a JAR that bundles some or all of its dependencies with it. This may be fine if the dependencies are shaded (i.e., their packages are renamed). But in many cases such as the JRuby and Jython uberjars, at least some of the dependencies are not shaded. This causes problems because there are often then multiple versions of the same library available on the classpath from multiple fat jars. To avoid this problem, the Fiji update site should not include any such unshaded fat jars, but instead ship only individual JAR libraries for all its components.

**Comment by ctrueden** [comment]
Progress:
* https://github.com/scijava/pom-scijava/commit/11c95964d49389be60b3b2b380b08f75d73cbbf8
* https://github.com/fiji/Simple_Neurite_Tracer/commit/82ba66f474ca445429ed5134486ff6c8bf69f0c9
* https://github.com/fiji/TrackMate/commit/af5bb362c94cffd3250fe1a07843d287035687ac
* https://github.com/fiji/IO/commit/370e18d009738972c427c289e007c78296fe6c0a

Releases coming soon!

**Comment by ctrueden** [comment]
All is complete, and uploaded to the Java-8 update site. However, there is currently a bug in the updater which prevents marking files obsolete on downstream update sites. So, I cannot remove the old batik uber-JAR yet. As soon as we find a workaround, I'll close this issue.

**Comment by bramalingam** [comment]
@ctrueden : The workflow (of opening an .msr file with the Java8 update site enabled) works without any issues on the Bio-Formats side, on Windows.

**Comment by ctrueden** [comment]
@bramalingam Thanks for the feedback. Glad it is working for your needs. I will close this issue now since all is resolved on the coding side. The removal of the `batik` uber-JAR will take place when we migrate the Java-8 components back to the core Fiji and ImageJ update sites, hopefully soon.
